### ISSUE TITLE
Window not closed after transfer

### ISSUE THREAD

**Issue by butu** [hakito/PHP-Stuzza-EPS-BankTransfer#17]
When transfer is (successfully) completed and one clicks "logout and return to shop", you get redirected to https://eps.raiffeisen.at/html/common/themes/logout/redirectOpenerAndCloseSelf.jsp and nothing happens.

JS Console of this page says: Scripts may close only the windows that were opened by it.

**Comment by hakito** [comment]
I think the problem comes from Raiffeisen implementation in this case. The PHP-Stuzza-EPS-BankTranser does not open any new windows (It can't). The bank has to return the customer to the return URL indicated in TransferMsgDetails.

Did you forward the client in a new browser window to the payment URL?

**Comment by hakito** [comment]
Closing because of missing feedback.
